services:
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
    restart: unless-stopped


  lnbits:
    image: lnbits/lnbits:v1.5.6
    env_file: ./lnbits.env
    ports:
      - "5000:5000"
    environment:
      - LNBITS_BACKEND_WALLET_CLASS=FakeWallet   
      - LNBITS_SITE_TITLE=SatsMeter
    volumes:
      - lnbits_data:/app/data
    restart: unless-stopped

volumes:
  lnbits_data:
